RecipesWeb/Controllers/SignUpController.cs
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using RecipesCore.Models;
using RecipesCore.Services;
using RecipesWeb.ViewModels;

namespace RecipesWeb.Controllers
{
    public class SignUpController : BaseController
    {
        private readonly IUserService _userService;
        private readonly IIngredientService _ingredientService;

        public SignUpController(IUserService userService, IIngredientService ingredientService)
        {
            _userService = userService;
            _ingredientService = ingredientService;
        }
        
        public IActionResult Show()
        {
            return View(PrepareViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> SignUp(string userLogin, string vegetarian, string vegan, string allergies,
            [Bind] RegisterViewModel registerViewModel)
        {
            var ingredients = _ingredientService.GetAll();
            var username = userLogin;
            if (string.IsNullOrWhiteSpace(username) || _userService.Exists(userLogin))
            {
                return Redirect("/Error");
            }
            
            bool bVegetarian = vegetarian?.Equals("on") ?? false;
            bool bVegan = vegan?.Equals("on") ?? false;
            var allergiesList = registerViewModel.Ingredients
                .Where(i => i.Selected)
                .Select(i => ingredients.First(j => j.Id == i.Id))
                .Select(i => new UserAllergie(i))
                .ToList();
            User user = new User(username, bVegetarian, bVegan, allergiesList);
            _userService.Add(user);
            
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, username),
                new Claim(ClaimTypes.Role, "User")
            };
            var identity = new ClaimsIdentity(claims);
            var principal = new ClaimsPrincipal(identity);

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
            
            return Redirect("/");
        }

        private RegisterViewModel PrepareViewModel()
        {
            var viewModel = new RegisterViewModel();
            _ingredientService.GetAllByPreference().ForEach(i =>
            {
                viewModel.Ingredients.Add(new SelectedItemViewModel { Id = i.Id, Name = i.Name });
            });

            return viewModel;
        }
    }
}

RecipesWeb/Views/SignUp/Show.cshtml
@using RecipesWeb.Tools
@model RecipesWeb.ViewModels.RegisterViewModel
@{
    ViewData["Title"] = "Sign up";
}

<div class="container">
    <form class="form-signin" asp-controller="SignUp" asp-action="SignUp" method="post">
        <h2 class="form-signin-heading"><i class="fa fa-cutlery"></i> Sign up</h2>
        
        <div class="form-group">
            <input type="text" name="userLogin" id="userLogin" class="form-control" placeholder="Username" required autofocus>
        </div>

        <div class="row"></div>

        <h3>Info about you</h3>
        <!--
        <div class="checkbox">
            <label> <input type="checkbox" name="vegetarian"> Vegetarian </label>
        </div>
        
        <div class="checkbox">
            <label> <input type="checkbox" name="vegan"> Vegan </label>
        </div>
        -->
        
        <div class="form-group">
            <label for="allergies">
                Please, tell us which ingredients you are allergic to or you strongly dislike:
            </label>
            
            <div class="allergiesList">
                @for (var i = 0; i < Model.Ingredients.Count; i++)
                {
                    <div>
                        <input type="hidden"
                               asp-for="@Model.Ingredients[i].Id" />
                        <input type="checkbox"
                               id="Ingredients_@(i)__Selected"
                               asp-for="@Model.Ingredients[i].Selected"/>
                        <label asp-for="@Model.Ingredients[i].Selected">
                            @Model.Ingredients[i].Name.CapitalizeFirst()
                        </label>
                    </div>
                }
            </div>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
    </form>
    
</div>

<div class="container">
    <div class="row">
        <div class="col-xs-10 col-sm-12 col-md-10 col-lg-4 col-centered text-center">
            <a asp-controller="SignUp" asp-action="Show">Are you already registered? Log in.</a>
        </div>
    </div>
</div>