RecipesWeb/Controllers/LoginController.cs
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using RecipesCore.Services;

namespace RecipesWeb.Controllers
{
    public class LoginController : BaseController
    {
        private readonly IUserService _userService;

        public LoginController(IUserService userService)
        {
            _userService = userService;
        }

        public IActionResult Show()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> LogIn(string userLogin)
        {
            var username = userLogin;
            if (string.IsNullOrWhiteSpace(username) || !_userService.Exists(userLogin))
            {
                return Redirect("/Error");
            }

            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, username),
                new Claim(ClaimTypes.Role, "User")
            };
            var identity = new ClaimsIdentity(claims);
            var principal = new ClaimsPrincipal(identity);

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
            return Redirect("/");
        }

        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return Redirect("/");
        }
    }
}

RecipesWeb/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using RecipesCore;
using RecipesWeb.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace RecipesWeb.Controllers
{
    public class SearchController : BaseController
    {
        private readonly RecipesContext db;
        //private FilterViewModel filter;

        public SearchController(RecipesContext db)
        {
            this.db = db;

        }

        public IActionResult Show(FilterViewModel filter)
        {
            if (filter.Categories == null) { 
                var cat = db.Categories.ToList().Select(x =>
                                                    new SelectListItem
                                                    {
                                                        Value = x.Id.ToString(),
                                                        Text = x.Name
                                                    });
            
                filter = new FilterViewModel
                {
                    //Ingredients = db.Ingredients.ToList(),
                    Selected = new Dictionary<string, bool> { { "egg", false }, { "water", false }, { "floor", false },
                         { "mashrooms", false },  { "oil", false },  { "spenat", false },  { "brokoli", false } },
                    Categories = new SelectList(cat, "Value", "Text"),
                    Ingred = new List<String> { "egg", "water", "floor", "mashrooms", "oil", "spenat", "brokoli" },
                    Recipes = db.Recipes.ToList()
                };
            }
            if (filter.CategoryId != null)
            {
                filter.Recipes = db.Recipes.Where(r => r.Category.Id == filter.CategoryId).ToList();
            }
            return View(filter);
        }
    }
}

RecipesWeb/Controllers/SystemController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using RecipesCore.Info;
using RecipesCore.Services;

namespace RecipesWeb.Controllers
{
    public class SystemController : BaseController
    {
        private readonly IRecipesService _recipesService;
        private readonly ICategoryService _categoryService;
        private readonly IIngredientService _ingredientService;

        public SystemController(IRecipesService recipesService, ICategoryService categoryService, IIngredientService ingredientService)
        {
            _recipesService = recipesService;
            _categoryService = categoryService;
            _ingredientService = ingredientService;
        }

        public IActionResult Info()
        {
            ViewBag.RecipesCount = _recipesService.Count();
            ViewBag.CategoriesCount = _categoryService.Count();
            ViewBag.TopDislikedIngredients = _ingredientService.GetAllByPreference().Take(5);
            ViewBag.Algorithms = RecommendingAlgorithms.GetAll();
            ViewBag.Algorithm = Algorithm;
            return View();
        }

        public IActionResult SwitchAlgorithm(string identifier)
        {
            SetAlgorithm(identifier);
            return RedirectToAction("Info");
        }
    }
}

RecipesWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyRecipes</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">
                    <i class="fa fa-cutlery"></i>
                    MyRecipes
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a asp-area="" asp-controller="Home" asp-action="Index">
                            <i class="fa fa-home"></i>
                            Home
                        </a>
                    </li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-folder-open"></i>
                            Categories <span class="caret"></span>
                        </a>

                        <ul class="dropdown-menu">
                            @await Component.InvokeAsync("CategoryMenu")
                        </ul>
                    </li>
                </ul>
                <!--
                <ul class="nav navbar-nav">
                    <li>
                        <a asp-area="" asp-controller="Search" asp-action="Show">
                            <i class="fa fa-search"></i>
                            Search
                        </a>
                    </li>
                </ul>
                -->
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        @if (!User.IsInRole("User"))
            {
                <a asp-area="" asp-controller="Login" asp-action="Show">
                    <i class="glyphicon glyphicon-log-in"></i>&nbsp;Log In
                </a>
}
else
{
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                   aria-haspopup="true" aria-expanded="false">
                    <i class="glyphicon glyphicon-user"></i> @User.Identity.Name
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="https://github.com/pv254/recipes" target="_blank">
                            <i class="glyphicon glyphicon-info-sign"></i>&nbsp;About the application
                        </a>
                    </li>
                    <li role="separator" class="divider"></li>
                    <li>
                        <a asp-controller="Login" asp-action="LogOut">
                            <i class="glyphicon glyphicon-log-out"></i>&nbsp;Log out
                        </a>
                    </li>
                </ul>
            </li>
}
                        </li>
                    </ul>
                </div>
            
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>
                MyRecipes 2017
                |
                <i class="fa fa-cog"></i>
                <a asp-controller="System" asp-action="Info">System Information</a>
            </p>
        </footer>
    </div>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>